import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import LeftPane from "../components/LeftPane";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NextTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <LeftPane />
    </div>
  );
};

export default Home;
